using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace InfrastructureApp.Models
{
    //This maps to the ERD's Report Table
    public class ReportIssue : IValidatableObject
    {
        //PK Identity
        public int Id { get; set; }

        //NVARCHAR(MAX)
        [Required(ErrorMessage = "Please enter a description.")]
        [StringLength(300, ErrorMessage = "Description must be 300 characters or less.")]
        [MaxLength(300, ErrorMessage = "Description must be 300 characters or less.")]
        [Display(Name = "Description")]
        public string Description { get; set; } = string.Empty;

        //NVARCHAR(50): Pending, Approved, Rejected
        [MaxLength(50)]

        public string Status { get; set; } = "Approved";

        //DATETIME2
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        //FK to ApsNetUser.Id (nvarchar(450))
        public string UserId { get; set; } = "";

        //DECIMAL(9,6)
        //[Required(ErrorMessage = "Please select a location on the map to populate Latitude.")]   //for testing
        [Range(-90, 90, ErrorMessage = "Latitude must be between -90 and 90.")]
        public decimal? Latitude { get; set; }

        //DECIMAL (9,6)
        //[Required(ErrorMessage = "Please select a location on the map to populate Longitude.")]   //for testing
        [Range(-180, 180, ErrorMessage = "Longitude must be between -180 and 180.")]
        public decimal? Longitude { get; set; }

        //NVARCHAR(450) (URL to blob)
        [MaxLength(450)]
        public string? ImageUrl { get; set; }

        // SHA-256 hash stored as a 64-character hex string.
        // This is for EXACT duplicate detection.
        [MaxLength(64)]
        public string? ImageSha256 { get; set; }

        // Stores the perceptual hash as a signed 64-bit integer.
        // Perceptual hash stored as long (SQL bigint).
        // This is for VISUAL similarity detection.
        public long? ImagePHash { get; set; }

        //severity status of image
        [MaxLength(20)]
        public string SeverityStatus { get; set; } = "Pending";

        //severity reason generated by AI
        [MaxLength(1000)]
        public string? SeverityReason { get; set; }

        public virtual ICollection<ReportFlag> ReportFlags { get; set; } = new List<ReportFlag>();


        // ----------------------------------------------------
        // UI-only properties for form submission
        // Not mapped to the database
        // ----------------------------------------------------

        [Display(Name = "Photo")]
        [NotMapped]
        public IFormFile? Photo { get; set; }

        [NotMapped]
        public string? CameraId { get; set; }

        [NotMapped]
        public string? CameraImageUrl { get; set; }

        // ----------------------------------------------------
        // Conditional validation for form submission
        // Require either an uploaded photo OR a camera image URL
        // ----------------------------------------------------
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var hasUploadedPhoto = Photo != null && Photo.Length > 0;
            var hasCameraImage = !string.IsNullOrWhiteSpace(CameraImageUrl);

            if (!hasUploadedPhoto && !hasCameraImage)
            {
                yield return new ValidationResult(
                    "Please upload a photo of the damage.",
                    new[] { nameof(Photo) });
            }

            if (Latitude == null)
            {
                yield return new ValidationResult(
                    "Please select a location on the map to populate Latitude.",
                    new[] { nameof(Latitude) });
            }

            if (Longitude == null)
            {
                yield return new ValidationResult(
                    "Please select a location on the map to populate Longitude.",
                    new[] { nameof(Longitude) });
            }
        }


        // ----------------------------------------------------
        // Report query helpers
        // Keep filtering and sorting logic here instead of the controller
        // Moved it to here because this keeps controllers simple and separates data logic from UI logic
        // ----------------------------------------------------

        // Determines which reports should be visible to the user
        public static IQueryable<ReportIssue> VisibleToUser(IQueryable<ReportIssue> query, bool isAdmin)
        {
            // Admin sees all reports; others see only approved ones
            if (isAdmin)
            {
                return query;
            }

            return query.Where(r => r.Status == "Approved");
        }

        // Orders reports so the newest appear first
        public static IQueryable<ReportIssue> OrderLatestFirst(IQueryable<ReportIssue> query)
        {
            // Sort by creation date (newest first)
            return query.OrderByDescending(r => r.CreatedAt);
        }

        // Filters by keyword in Description (case-insensitive)
        public static IQueryable<ReportIssue> FilterByDescription(IQueryable<ReportIssue> query, string? keyword)
        {
            if (string.IsNullOrWhiteSpace(keyword))
            {
                return query;
            }

            keyword = keyword.Trim().ToLower();

            // Case-insensitive matching
            return query.Where(r => r.Description != null && r.Description.ToLower().Contains(keyword));
        }

        // Applies sorting based on selected sort option
        // SCRUM-86 ADDED: allows sorting newest or oldest without putting logic in controller
        public static IQueryable<ReportIssue> ApplyDateSort(IQueryable<ReportIssue> query, string? sort)
        {
            // SCRUM-86 ADDED: oldest-first option
            if (!string.IsNullOrWhiteSpace(sort) && sort.Trim().ToLower() == "oldest")
            {
                return query.OrderBy(r => r.CreatedAt);
            }

            // default behavior (newest-first)
            return query.OrderByDescending(r => r.CreatedAt);
        }

        // SCRUM-126: Shortens report descriptions for Home page preview 
        public static string BuildDescriptionPreview(string? description, int previewLength = 60)
        {
            // Return empty if null or whitespace
            if (string.IsNullOrWhiteSpace(description))
            {
                return string.Empty;
            }

             // Remove extra spaces from start/end
            var trimmedDescription = description.Trim();

            // If short enough, return as-is
            if (trimmedDescription.Length <= previewLength)
            {
                return trimmedDescription;
            }

            // Otherwise, cut and add "..."
            return trimmedDescription.Substring(0, previewLength).TrimEnd() + "...";
        }

        // SCRUM-127:
        // Builds relative time text for Home page recent reports
        public static string BuildRelativeTime(DateTime createdAt, DateTime currentTime)
        {
            var timeDifference = currentTime - createdAt;

            if (timeDifference.TotalMinutes < 1)
            {
                return "Just now";
            }

            if (timeDifference.TotalMinutes < 60)
            {
                return $"{(int)timeDifference.TotalMinutes} minutes ago";
            }

            if (timeDifference.TotalHours < 24)
            {
                return $"{(int)timeDifference.TotalHours} hours ago";
            }

            return $"{(int)timeDifference.TotalDays} days ago";
        }
    }
}
