name: PR Gatekeeper

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          
      - name: Restore dependencies
        run: dotnet restore src/InfrastructureApp_Tests

      - name: Build
        run: dotnet build src/InfrastructureApp_Tests --no-restore

      - name: Test
        run: dotnet test src/InfrastructureApp_Tests --no-build --verbosity normal

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x' 

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/InfrastructureApp_TestsJS

      - name: Run frontend tests
        run: npm test
        working-directory: ./src/InfrastructureApp_TestsJS